package com.engine.editor.ffmpeg;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assumptions;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

class FFprobeMediaAnalyzerTest {

    private final FFprobeMediaAnalyzer analyzer = new FFprobeMediaAnalyzer();

    /**
     * Regression test for VP9+alpha detection via the alpha_mode=1 stream tag.
     *
     * The test video was generated by mock-data-generator/generate.py:
     *   python generate.py --max 1 --shapes rectangle --colors blue \
     *       --positions top --sizes 320x240 --durations 1.0 \
     *       --texts clip_alpha_test
     * and saved as src/test/resources/vp9_alpha_mode_tag.webm.
     *
     * VP9+alpha WebM encodes the alpha plane as block additions within a single
     * video track. ffprobe reports pix_fmt=yuv420p (not yuva420p) for such files
     * and sets alpha_mode=1 in the stream's tag metadata instead of using a
     * second video stream. Without checking this tag, hasAlpha was always false
     * for generator-produced clips, causing every non-bottom layer to be flagged
     * with "Non-bottom layer must have alpha channel" in the editor.
     */
    @Test
    void detectsAlphaFromVp9AlphaModeTag() throws IOException, URISyntaxException {
        Assumptions.assumeFalse(Boolean.parseBoolean(System.getenv("GITHUB_ACTIONS")),
                "Skipping ffprobe-dependent test on GitHub Actions");

        Path file = Path.of(getClass().getClassLoader()
                .getResource("vp9_alpha_mode_tag.webm").toURI());

        MediaInfo info = analyzer.analyze(file);

        assertEquals("video", info.getMediaType());
        assertEquals("vp9", info.getCodec());
        assertTrue(info.isHasAlpha(),
                "Expected hasAlpha=true for VP9 WebM with alpha_mode=1 tag, " +
                "but got false — pix_fmt alone (" + info.getPixelFormat() + ") " +
                "is insufficient to detect VP9+alpha");
    }
}
