export function createRuntimeContext(doc = document) {
  const $ = (id) => doc.getElementById(id);

  const defaultSettings = {
    musicVolume: 0.7,
    videoVolume: 1.0,
    musicEnabled: true,
    btnBg: '#000000',
    btnText: '#ffffff',
    btnPosition: 'bottom',
    resolution: 'auto',
    subtitlesEnabled: true,
    locale: '',
  };

  return {
    doc,
    $,
    defaultSettings,
    settings: { ...defaultSettings },
    state: {
      currentState: null,
      hlsInstance: null,
      transHls: null,
      countdownTimer: null,
      decisionMade: false,
      preloadedHls: {},
      preloadedSceneHls: {},
      currentMusicUrl: null,
      gamePaused: false,
      loopHandler: null,
      sceneVideoListeners: [],
      activeDecisionHotkeys: new Map(),
      appScreen: 'menu',
      settingsReturnTo: 'menu',
      currentSubtitles: [],
      subtitleRafId: null,
    },
    dom: {
      mainMenu: $('main-menu'),
      gameScreen: $('game-screen'),
      pauseOverlay: $('pause-overlay'),
      settingsOverlay: $('settings-overlay'),
      videoEl: $('video-el'),
      transEl: $('transition-el'),
      freezeCanvas: $('freeze-canvas'),
      decisionOverlay: $('decision-overlay'),
      decisionButtons: $('decision-buttons'),
      decisionInputIndicator: $('decision-input-indicator'),
      countdownEl: $('countdown'),
      countdownNum: $('countdown-num'),
      countdownArc: $('countdown-arc'),
      spinner: $('spinner'),
      spinnerText: $('spinner-text'),
      errorBox: $('error-box'),
      errorMsg: $('error-msg'),
      endScreen: $('end-screen'),
      musicEl: $('music-el'),
      pauseBtn: $('pause-btn'),
      subtitleContainer: $('subtitle-container'),
      subtitleText: $('subtitle-text'),
      settingMusicVol: $('setting-music-vol'),
      settingVideoVol: $('setting-video-vol'),
      settingMusicEnabled: $('setting-music-enabled'),
      settingBtnBg: $('setting-btn-bg'),
      settingBtnText: $('setting-btn-text'),
      settingBtnPos: $('setting-btn-pos'),
      settingResolution: $('setting-resolution'),
      settingSubtitlesEnabled: $('setting-subtitles-enabled'),
      settingLocale: $('setting-locale'),
      musicVolDisplay: $('music-vol-display'),
      videoVolDisplay: $('video-vol-display'),
      btnBgDisplay: $('btn-bg-display'),
      btnTextDisplay: $('btn-text-display'),
    },
  };
}
